name: Verify and Promote Dev to Main

on:
  push:
    branches:
      - Dev

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # You can change to your version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask app tests (optional)
        run: |
          # If you have tests, run them here. If not, remove this step.
          echo "Run tests here like pytest or unittest"
          # Example: pytest

  promote:
    needs: verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.DEV_MAIN_PUSH }} 

      - name: Configure Git
        run: |
          git config user.name "sumit-essi"
          git config user.email "sumitpoonia.essi@gmail.com"

      - name: Merge Dev into main
        run: |
          git fetch origin Dev
          git merge origin/Dev --no-edit

      - name: Push changes to main
        env:
          TOKEN: ${{ secrets.DEV_MAIN_PUSH }}
        run: |
          git push https://secrets.DEV_MAIN_PUSH@github.com/sumit-essi/test HEAD:main
